### ISSUE TITLE
StackOverflowError: FollowingInputStream.handle

### ISSUE THREAD

**Issue by jdrews** [alaz/tailf#2]
Ran into a StackOverflowError while letting this tail a file for a while (over 10 min). Log file was idle the entire time. 

```
Exception in thread "Thread-10" java.lang.StackOverflowError
    at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:253)
    at com.osinka.tailf.FollowingInputStream.rotated_$qmark(Tail.scala:104)
    at com.osinka.tailf.FollowingInputStream.handle(Tail.scala:109)
at com.osinka.tailf.FollowingInputStream.handle(Tail.scala:112)
    at com.osinka.tailf.FollowingInputStream.handle(Tail.scala:112)
    at com.osinka.tailf.FollowingInputStream.handle(Tail.scala:112)
    at com.osinka.tailf.FollowingInputStream.handle(Tail.scala:112)
    at com.osinka.tailf.FollowingInputStream.handle(Tail.scala:112)
```

followed by a ton of FollowingInputStream.handle lines. There are a total of 1020 of the following lines in the stacktrace:
`at com.osinka.tailf.FollowingInputStream.handle(Tail.scala:112)`

 Full stacktrace here: http://pastebin.com/YEyrWnFv

Using Java 1.6u45 and Scala 2.10.4

I called Tail like this

``` scala
    def read(r: BufferedReader): Unit = {
        if (!Thread.currentThread().isInterrupted) {
            val l = r.readLine
            if (l != null) {
                log.info(s"read line: $l")
            }
            read(r)
        } else {
            r.close()
            log.info("read() Shutdown!")
        }
    }

val file: File = new File(logFile)
val r = new BufferedReader(new InputStreamReader(Tail.follow(file)))
val readerThread = new Thread(new Runnable {
                def run() {
                    read(r)
                }
            })

readerThread.setDaemon(true)
readerThread.start()
```

**Comment by jdrews** [comment]
Hmm I wonder if the issue is on my end. Did I do something stupid with my calling of read() recursively... I'm going to look into alternatives.

**Comment by jdrews** [comment]
Alright I reworked the read to loop. That seemed to fix it... So it must have been me. 

``` scala
  def loopRead(r: BufferedReader, logFile: String): Unit = {
    while (!Thread.currentThread().isInterrupted) {
      val l = r.readLine
      if (l != null) {
        log.info(s"read line: $l")
      }
    }
    r.close()
    log.info("loopRead() shutdown!")
  }
```

**Comment by alaz** [comment]
Thanks for letting know!

**Comment by jdrews** [comment]
Sorry to say this happened again... with the while loops in place instead of the recursive calls. So I'm reopening the issue...

**Comment by alaz** [comment]
Try to explicitly mark `FollowingInputStream.handle` as tail recursive:

```
    @tailrec
    protected final def handle(read: => Int): Int = ....
```

**Comment by jdrews** [comment]
Thanks! I left it tailing a blank file overnight and it did not crash. Had to mark the handle as final since the scala compiler threw this error otherwise:

```
Error:(127, 19) could not optimize @tailrec annotated method handle: it is neither private nor final so can be overridden
    protected def handle(read: => Int): Int = read match {
                  ^
```

``` scala
    @tailrec
    final protected def handle(read: => Int): Int = read match {
        case -1 if rotated_? || closed_? => -1
        case -1 =>
            waitNewInput()
            handle(read)
        case i => i
    }
```

**Comment by alaz** [comment]
:+1:
